// SPDX-FileCopyrightText: © 2025 Logan Magee
//
// SPDX-License-Identifier: Apache-2.0

syntax = "proto3";

package accrescent.console.v1;

import "accrescent/console/v1/create_app_draft_listing_request.proto";
import "accrescent/console/v1/create_app_draft_listing_response.proto";
import "accrescent/console/v1/create_app_draft_request.proto";
import "accrescent/console/v1/create_app_draft_response.proto";
import "accrescent/console/v1/delete_app_draft_listing_request.proto";
import "accrescent/console/v1/delete_app_draft_listing_response.proto";
import "accrescent/console/v1/delete_app_draft_request.proto";
import "accrescent/console/v1/delete_app_draft_response.proto";
import "accrescent/console/v1/download_app_draft_listing_icon_request.proto";
import "accrescent/console/v1/download_app_draft_listing_icon_response.proto";
import "accrescent/console/v1/download_app_draft_request.proto";
import "accrescent/console/v1/download_app_draft_response.proto";
import "accrescent/console/v1/get_app_draft_request.proto";
import "accrescent/console/v1/get_app_draft_response.proto";
import "accrescent/console/v1/list_app_drafts_request.proto";
import "accrescent/console/v1/list_app_drafts_response.proto";
import "accrescent/console/v1/publish_app_draft_request.proto";
import "accrescent/console/v1/publish_app_draft_response.proto";
import "accrescent/console/v1/submit_app_draft_request.proto";
import "accrescent/console/v1/submit_app_draft_response.proto";
import "accrescent/console/v1/update_app_draft_request.proto";
import "accrescent/console/v1/update_app_draft_response.proto";
import "accrescent/console/v1/upload_app_draft_listing_icon_request.proto";
import "accrescent/console/v1/upload_app_draft_listing_icon_response.proto";
import "accrescent/console/v1/upload_app_draft_request.proto";
import "accrescent/console/v1/upload_app_draft_response.proto";
import "google/api/annotations.proto";
import "google/api/client.proto";

option go_package = "golang.accrescent.app/genproto/accrescent/console/v1;console";
option java_multiple_files = true;
option java_package = "app.accrescent.console.v1";

// Service providing RPCs for managing app drafts.
service AppDraftService {
  option (google.api.default_host) = "console-api.accrescent.app";

  // Creates a new app draft.
  rpc CreateAppDraft(CreateAppDraftRequest) returns (CreateAppDraftResponse) {
    option (google.api.http) = {
      post: "/v1/app_drafts:create"
      body: "*"
    };
  }

  // Gets an app draft.
  rpc GetAppDraft(GetAppDraftRequest) returns (GetAppDraftResponse) {
    option idempotency_level = NO_SIDE_EFFECTS;
    option (google.api.http) = {
      post: "/v1/app_drafts/{app_draft_id}:get"
      body: "*"
    };
  }

  // Lists app drafts.
  rpc ListAppDrafts(ListAppDraftsRequest) returns (ListAppDraftsResponse) {
    option idempotency_level = NO_SIDE_EFFECTS;
    option (google.api.http) = {
      post: "/v1/app_drafts:list"
      body: "*"
    };
  }

  // Uploads an app draft.
  rpc UploadAppDraft(UploadAppDraftRequest) returns (UploadAppDraftResponse) {
    option (google.api.http) = {
      post: "/v1/app_drafts/{app_draft_id}:upload"
      body: "*"
    };
  }

  // Downloads an app draft.
  rpc DownloadAppDraft(DownloadAppDraftRequest) returns (DownloadAppDraftResponse) {
    option idempotency_level = NO_SIDE_EFFECTS;
    option (google.api.http) = {
      post: "/v1/app_drafts/{app_draft_id}:download"
      body: "*"
    };
  }

  // Updates an app draft.
  rpc UpdateAppDraft(UpdateAppDraftRequest) returns (UpdateAppDraftResponse) {
    option (google.api.http) = {
      post: "/v1/app_drafts/{app_draft_id}:update"
      body: "*"
    };
  }

  // Submits an app draft for review.
  rpc SubmitAppDraft(SubmitAppDraftRequest) returns (SubmitAppDraftResponse) {
    option idempotency_level = IDEMPOTENT;
    option (google.api.http) = {
      post: "/v1/app_drafts/{app_draft_id}:submit"
      body: "*"
    };
  }

  // Deletes an existing app draft.
  rpc DeleteAppDraft(DeleteAppDraftRequest) returns (DeleteAppDraftResponse) {
    option idempotency_level = IDEMPOTENT;
    option (google.api.http) = {
      post: "/v1/app_drafts/{app_draft_id}:delete"
      body: "*"
    };
  }

  // Creates a new app listing for an app draft.
  rpc CreateAppDraftListing(CreateAppDraftListingRequest) returns (CreateAppDraftListingResponse) {
    option (google.api.http) = {
      post: "/v1/app_draft_listings:create"
      body: "*"
    };
  }

  // Uploads an app draft listing icon.
  rpc UploadAppDraftListingIcon(UploadAppDraftListingIconRequest) returns (UploadAppDraftListingIconResponse) {
    option (google.api.http) = {
      post: "/v1/app_draft_listings/{app_draft_listing_id}/icon:upload"
      body: "*"
    };
  }

  // Downloads an app draft listing icon.
  rpc DownloadAppDraftListingIcon(DownloadAppDraftListingIconRequest) returns (DownloadAppDraftListingIconResponse) {
    option idempotency_level = NO_SIDE_EFFECTS;
    option (google.api.http) = {
      post: "/v1/app_draft_listings/{app_draft_listing_id}/icon:download"
      body: "*"
    };
  }

  // Deletes an existing app draft listing.
  rpc DeleteAppDraftListing(DeleteAppDraftListingRequest) returns (DeleteAppDraftListingResponse) {
    option idempotency_level = IDEMPOTENT;
    option (google.api.http) = {
      post: "/v1/app_draft_listings/{app_draft_listing_id}:delete"
      body: "*"
    };
  }

  // Publishes an app draft to the app store.
  rpc PublishAppDraft(PublishAppDraftRequest) returns (PublishAppDraftResponse) {
    option idempotency_level = IDEMPOTENT;
    option (google.api.http) = {
      post: "/v1/app_drafts/{app_draft_id}:publish"
      body: "*"
    };
  }
}
