// SPDX-FileCopyrightText: © 2026 Logan Magee
//
// SPDX-License-Identifier: Apache-2.0

syntax = "proto3";

package accrescent.console.v1;

import "accrescent/console/v1/create_app_edit_listing_request.proto";
import "accrescent/console/v1/create_app_edit_listing_response.proto";
import "accrescent/console/v1/create_app_edit_request.proto";
import "accrescent/console/v1/create_app_edit_response.proto";
import "accrescent/console/v1/delete_app_edit_listing_request.proto";
import "accrescent/console/v1/delete_app_edit_listing_response.proto";
import "accrescent/console/v1/delete_app_edit_request.proto";
import "accrescent/console/v1/delete_app_edit_response.proto";
import "accrescent/console/v1/download_app_edit_request.proto";
import "accrescent/console/v1/download_app_edit_response.proto";
import "accrescent/console/v1/get_app_edit_request.proto";
import "accrescent/console/v1/get_app_edit_response.proto";
import "accrescent/console/v1/list_app_edit_listings_request.proto";
import "accrescent/console/v1/list_app_edit_listings_response.proto";
import "accrescent/console/v1/list_app_edits_request.proto";
import "accrescent/console/v1/list_app_edits_response.proto";
import "accrescent/console/v1/submit_app_edit_request.proto";
import "accrescent/console/v1/submit_app_edit_response.proto";
import "accrescent/console/v1/update_app_edit_listing_request.proto";
import "accrescent/console/v1/update_app_edit_listing_response.proto";
import "accrescent/console/v1/update_app_edit_request.proto";
import "accrescent/console/v1/update_app_edit_response.proto";
import "accrescent/console/v1/upload_app_edit_listing_icon_request.proto";
import "accrescent/console/v1/upload_app_edit_listing_icon_response.proto";
import "accrescent/console/v1/upload_app_edit_request.proto";
import "accrescent/console/v1/upload_app_edit_response.proto";
import "google/api/client.proto";

option go_package = "golang.accrescent.app/genproto/accrescent/console/v1;console";
option java_multiple_files = true;
option java_package = "app.accrescent.console.v1";

// Service providing RPCs for managing app edits.
service AppEditService {
  option (google.api.default_host) = "console-api.accrescent.app";

  // Creates a new app edit.
  rpc CreateAppEdit(CreateAppEditRequest) returns (CreateAppEditResponse) {}

  // Gets an app edit.
  rpc GetAppEdit(GetAppEditRequest) returns (GetAppEditResponse) {
    option idempotency_level = NO_SIDE_EFFECTS;
  }

  // Lists app edits.
  rpc ListAppEdits(ListAppEditsRequest) returns (ListAppEditsResponse) {
    option idempotency_level = NO_SIDE_EFFECTS;
  }

  // Uploads an app edit APK set.
  rpc UploadAppEdit(UploadAppEditRequest) returns (UploadAppEditResponse) {}

  // Downloads an app edit.
  rpc DownloadAppEdit(DownloadAppEditRequest) returns (DownloadAppEditResponse) {
    option idempotency_level = NO_SIDE_EFFECTS;
  }

  // Updates an app edit.
  rpc UpdateAppEdit(UpdateAppEditRequest) returns (UpdateAppEditResponse) {}

  // Submits an app edit.
  rpc SubmitAppEdit(SubmitAppEditRequest) returns (SubmitAppEditResponse) {
    option idempotency_level = IDEMPOTENT;
  }

  // Deletes an app edit.
  rpc DeleteAppEdit(DeleteAppEditRequest) returns (DeleteAppEditResponse) {
    option idempotency_level = IDEMPOTENT;
  }

  // Creates a new app listing for an app edit.
  rpc CreateAppEditListing(CreateAppEditListingRequest) returns (CreateAppEditListingResponse) {}

  // Lists app edit listings.
  rpc ListAppEditListings(ListAppEditListingsRequest) returns (ListAppEditListingsResponse) {
    option idempotency_level = NO_SIDE_EFFECTS;
  }

  // Updates an app edit listing.
  rpc UpdateAppEditListing(UpdateAppEditListingRequest) returns (UpdateAppEditListingResponse) {}

  // Uploads an app edit listing icon.
  rpc UploadAppEditListingIcon(UploadAppEditListingIconRequest) returns (UploadAppEditListingIconResponse) {}

  // Deletes an existing app edit listing.
  rpc DeleteAppEditListing(DeleteAppEditListingRequest) returns (DeleteAppEditListingResponse) {
    option idempotency_level = IDEMPOTENT;
  }
}
