// SPDX-FileCopyrightText: © 2025 Logan Magee
//
// SPDX-License-Identifier: Apache-2.0

syntax = "proto3";

package accrescent.console.v1;

import "accrescent/console/v1/app_package.proto";
import "buf/validate/validate.proto";
import "google/protobuf/timestamp.proto";

option go_package = "golang.accrescent.app/genproto/accrescent/console/v1;console";
option java_multiple_files = true;
option java_package = "app.accrescent.console.v1";

// An app draft.
message AppDraft {
  // The app draft's unique ID.
  optional string id = 1 [(buf.validate.field).required = true];

  // The timestamp at which the app draft was created.
  google.protobuf.Timestamp create_time = 2 [(buf.validate.field).required = true];

  // The draft's default listing language, if set.
  optional string default_listing_language = 3;

  // The draft's associated package information, if available.
  AppPackage app_package = 4;

  // The operation ID of the latest upload for this app draft.
  optional string latest_upload_operation_id = 5;

  // The timestamp at which the app draft has been submitted for review, if
  // applicable.
  google.protobuf.Timestamp submit_time = 6;

  // The timestamp at which the app draft has been published, if applicable.
  google.protobuf.Timestamp publish_time = 7;

  option (buf.validate.message).cel = {
    id: "latest_upload_operation_id.requires_unsubmitted"
    message: "latest upload operation ID may be present only for unsubmitted app drafts"
    expression: "has(this.latest_upload_operation_id) ? !has(this.submit_time) : true"
  };

  option (buf.validate.message).cel = {
    id: "submit_time.requires_listing_language_and_package"
    message: "submitted app drafts must have default_listing_language and app_package set"
    expression:
      "has(this.submit_time) "
      "? has(this.default_listing_language) && has(this.app_package) "
      ": true"
  };

  option (buf.validate.message).cel = {
    id: "publish_time.requires_submit_time"
    message: "published app drafts must be submitted"
    expression: "has(this.publish_time) ? has(this.submit_time) : true"
  };
}
