// SPDX-FileCopyrightText: © 2026 Logan Magee
//
// SPDX-License-Identifier: Apache-2.0

syntax = "proto3";

package accrescent.console.v1;

import "buf/validate/validate.proto";

option go_package = "golang.accrescent.app/genproto/accrescent/console/v1;console";
option java_multiple_files = true;
option java_package = "app.accrescent.console.v1";

// Response to downloading an app draft listing icon.
message DownloadAppDraftListingIconResponse {
  // The URL of the icon which can be retrieved with a simple HTTP GET.
  optional string icon_url = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uri = true
  ];
}
