// SPDX-FileCopyrightText: © 2026 Logan Magee
//
// SPDX-License-Identifier: Apache-2.0

syntax = "proto3";

package accrescent.console.v1;

import "buf/validate/validate.proto";

option go_package = "golang.accrescent.app/genproto/accrescent/console/v1;console";
option java_multiple_files = true;
option java_package = "app.accrescent.console.v1";

// Request defining parameters for listing app listings.
message ListAppListingsRequest {
  // The app containing the listings to list.
  optional string app_id = 1 [(buf.validate.field).required = true];

  // The maximum number of app listings to return in the response. If
  // unspecified, defaults to 50. All requests with a higher page size will be
  // capped to 50.
  optional uint32 page_size = 2;

  // An opaque page continuation token returned in a previous
  // ListAppListingsResponse. If unspecified, the first page is returned.
  optional string page_token = 3;
}
