// SPDX-FileCopyrightText: © 2025 Logan Magee
//
// SPDX-License-Identifier: Apache-2.0

syntax = "proto3";

package accrescent.console.v1;

import "buf/validate/validate.proto";
import "google/longrunning/operations.proto";

option go_package = "golang.accrescent.app/genproto/accrescent/console/v1;console";
option java_multiple_files = true;
option java_package = "app.accrescent.console.v1";

// Response to uploading an app draft.
message UploadAppDraftResponse {
  // An HTTP or HTTPS URI at which an APK set can be submitted with an HTTP PUT
  // request.
  optional string apk_set_upload_uri = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uri = true
  ];

  // The upload processing operation.
  //
  // The response type of this operation is UploadAppDraftResult.
  google.longrunning.Operation processing_operation = 2 [(buf.validate.field).required = true];
}
