// SPDX-FileCopyrightText: © 2026 Logan Magee
//
// SPDX-License-Identifier: Apache-2.0

syntax = "proto3";

package accrescent.console.v1;

import "accrescent/console/v1/user_role.proto";
import "buf/validate/validate.proto";

option go_package = "golang.accrescent.app/genproto/accrescent/console/v1;console";
option java_multiple_files = true;
option java_package = "app.accrescent.console.v1";

// A console user.
message User {
  // The user's unique ID.
  optional string id = 1 [(buf.validate.field).required = true];

  // The user's email.
  optional string email = 2 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.email = true
  ];

  // The user's roles.
  repeated UserRole roles = 3 [
    (buf.validate.field).repeated.items.enum.not_in = 0,
    (buf.validate.field).repeated.unique = true
  ];
}
