// SPDX-FileCopyrightText: © 2026 Logan Magee
//
// SPDX-License-Identifier: Apache-2.0

syntax = "proto3";

package accrescent.console.v1alpha1;

import "accrescent/console/v1alpha1/get_app_request.proto";
import "accrescent/console/v1alpha1/get_app_response.proto";
import "accrescent/console/v1alpha1/list_apps_request.proto";
import "accrescent/console/v1alpha1/list_apps_response.proto";
import "accrescent/console/v1alpha1/update_app_request.proto";
import "accrescent/console/v1alpha1/update_app_response.proto";
import "google/api/annotations.proto";
import "google/api/client.proto";

option go_package = "golang.accrescent.app/genproto/accrescent/console/v1alpha1;console";
option java_multiple_files = true;
option java_package = "app.accrescent.console.v1alpha1";

// Service providing RPCs for managing published apps.
service AppService {
  option (google.api.default_host) = "console-api.accrescent.app";

  // Gets a published app.
  rpc GetApp(GetAppRequest) returns (GetAppResponse) {
    option idempotency_level = NO_SIDE_EFFECTS;
    option (google.api.http) = {get: "/v1alpha/apps/{app_id}"};
  }

  // Lists published apps.
  rpc ListApps(ListAppsRequest) returns (ListAppsResponse) {
    option idempotency_level = NO_SIDE_EFFECTS;
    option (google.api.http) = {get: "/v1alpha/apps"};
  }

  // Updates a published app.
  rpc UpdateApp(UpdateAppRequest) returns (UpdateAppResponse) {
    option (google.api.http) = {
      patch: "/v1alpha/apps/{app_id}"
      body: "*"
    };
  }
}
